services:
  front:
    build: "./app/"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    profiles: ["front"]
  api:
    build: "./api/"
    restart: always
    ports:
      - "1337:8090"
    volumes:
    - "bucket:/public/bucket"
    profiles: ["back"]
    depends_on:
      - db
  db:
    build: "./db/"
    restart: always
    expose:
      - "2137:5432"
    profiles: ["back", "db"]
volumes:
  bucket:
  db:
